### ISSUE TITLE
PSB breaks Membermouse plugin

### ISSUE THREAD

**Issue by zan5hin** [podlove/podlove-subscribe-button-wp-plugin#8] opened 2016-01-06 05:41 UTC
Hi gang,

I just spent a couple of hours trying to nail down the issue that is causing Membermouse to break on my site.  It unfortunately turns out ot be your plugin :(

I am building a site for a community radio station with 47 shows and 47 podcasts so I really need a one click button that can allow users of any device to subscribe to the podcasts.

This is a new site, my first WordPress site, so I am new to Membermouse and WP.  

I used a shortcode on the homepage to link to the "subscribe for a free membership level".  The user just has to enter in their details and then it should say "Thank you for your order"

However, it would never get to the thank you screen, it would give me a 404 error or sometimes a blank page when trying to access http://jair.cloudstorming.com.au/wp-content/plugins/membermouse/api/processOrder.php

I checked in CPanel, the file processOrder.php was there.

So they said contact my hosting provider, to which the hosting provider replied:

I believe it is a coding related issue. I found the following errors while accessing registering a free membership account. 

```
[Tue Jan 05 16:02:11 2016] [error] [client 103.4.16.57] [Tue Jan 5 16:02:08 2016, referer: http://jair.cloudstorming.com.au/checkout-1/?rid=maXTNM
[Tue Jan 05 16:02:11 2016] [error] [client 103.4.16.57] ] [notice] EACCELERATOR(191548): PHP crashed on opline 0 of add_action() at /home/omnicona/public_html/jair/wp-includes/plugin.php:457, referer: http://jair.cloudstorming.com.au/checkout-1/?rid=maXTNM
[Tue Jan 05 16:02:11 2016] [error] [client 103.4.16.57] , referer: http://jair.cloudstorming.com.au/checkout-1/?rid=maXTNM
[Tue Jan 05 16:02:11 2016] [error] [client 103.4.16.57] Premature end of script headers: processOrder.php, referer: http://jair.cloudstorming.com.au/checkout-1/?rid=maXTNM
```

To which Membermouse replied: 

Hi Adam,
When we attempt to access the page, we're seeing an internal server error:
http://www.screencast.com/t/NqagL4szQ3C

If the page loads and an error message is displayed, that would be indicative of a coding error. In this case, something in the server configuration is causing the error. Sometimes, situations like this are caused by misconfigured mod_rewrite rules.

I recommend enabling MemberMouse safe mode and walking through a test transaction:
http://support.membermouse.com/knowledgebase/articles/541840-using-safe-mode

If you're able to process a transaction in safe mode, that indicates that the theme or another plugin is involved in the error. Otherwise, you'll need to reach out to your hosting provider again.

=====

And this is how I found it it was PSB.  

I hope you can find a solution as I don't think there are many (or any) other plugins for WordPress similar to yours.

Any other questions let me know.  Sorry for the crazy big text, I don't know why it is doing that.

Also it is not a big deal but the plugin also has a problem with apostrophe in the name.  When you are adding a new button, it would be nice to have some text to tell you not to use apostrophes at the top.
Cheers

**Comment by timpritlove** [comment] 2016-01-06 07:00
None of the error messages refer to PSB. so why do you think it is related to our plugin?

**Comment by zan5hin** [comment] 2016-01-06 14:32
Because I went one by one through all my plugins, and it was only when I enabled PSB, that Membermouse stopped working.  If I disabled PSB, it started working again properly.

**Comment by timpritlove** [comment] 2016-01-06 15:08
We'll look into it although PSB does not much what should cause errors like this. Also the error occurs in Membermnouse's code so they should know better what can cause this problem.

>Also it is not a big deal but the plugin also has a problem with apostrophe in the name. When you are adding a new button, it would be nice to have some text to tell you not to use apostrophes at the top.

Can you explain what happens here? What "name" are you referring to? The podcast's title?

**Comment by timpritlove** [comment] 2016-01-06 15:09
(fixed the large type in your original post which was due to your stuff look like Markdown to GutHub)

**Comment by zan5hin** [comment] 2016-01-06 19:25
Any apostrophe in the ID field was an issue for me.

**Comment by chemiker** [comment] 2016-05-04 18:13
I see. This might be a result of an escaping problem. I'll see if this is reproducible and try to provide a fix in the next version.

**Comment by chemiker** [comment] 2016-05-04 18:18
However, I have to admit that I cannot reproduce the issue. Neither locally nor on a server configuration. Could you please provide more details on the server configuration (php Version, list of used plugins etc.)?

**Comment by chemiker** [comment] 2016-09-08 08:05
Since there has been no feedback for a while I'll close this issue. Please let me know if the issue persists.

**Closed by chemiker** 2016-09-08 08:05 UTC
