### ISSUE TITLE
Error when trying to save button

### ISSUE THREAD

**Issue by bryanbartow** [podlove/podlove-subscribe-button-wp-plugin#31] opened 2018-09-01 00:50 UTC
Getting this error:
`<br /><b>Notice</b>:  Trying to get property of non-object in <b>/nas/content/live/theyakkbryan/wp-content/plugins/podlove-subscribe-button/settings/buttons.php</b> on line <b>230</b><br />`

Attached screen shot which shows the error in all of the fields
<img width="1312" alt="screen shot 2018-08-31 at 7 49 02 pm" src="https://user-images.githubusercontent.com/867678/44940648-13c15f00-ad57-11e8-9499-a545d0edacd5.png">

**Comment by cfoellmann** [comment] 2018-09-01 07:27
I am not able to reproduce your error.

**Comment by cfoellmann** [comment] 2018-09-10 08:40
Can you please give me feedback on this with the latest 1.3.5 release via wp.org

**Comment by cfoellmann** [comment] 2018-10-03 18:42
@bryanbartow I will close this for now. Please reply if you still have issues

**Closed by cfoellmann** 2018-10-03 18:42 UTC
Labels: bug, support
